version: "3.8"

services:
#  app:
#    image: test_solution:latest
#    ports:
#      - "8080:8080"
#    build:
#      context: .
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
#      - SPRING_DATASOURCE_USERNAME=user
#      - SPRING_DATASOURCE_PASSWORD=pass
#    depends_on:
#      - db
  db:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - PGDATA=/data
    tmpfs:
      - /data
